In [1]:
import pandas as pd

da = pd.read_csv('/Users/rishitkapoor/Documents/Extra py/ML graph py/ML projects/Classification Problem/Multiclass/drug200.csv')

da1 = pd.read_csv('/Users/rishitkapoor/Documents/Extra py/ML graph py/ML projects/Classification Problem/Multiclass/drug200.csv')

da.head()

Age Sex      BP Cholesterol  Na_to_K   Drug
0   23   F    HIGH        HIGH   25.355  drugY
1   47   M     LOW        HIGH   13.093  drugC
2   47   M     LOW        HIGH   10.114  drugC
3   28   F  NORMAL        HIGH    7.798  drugX
4   61   F     LOW        HIGH   18.043  drugY

**Convert Text to Numerical Values**

In [2]:
mapping ={
    'LOW':0,
    'NORMAL':1,
    'HIGH':2
}

In [3]:
da.loc[:,'BP'] = da.BP.map(mapping)

In [4]:
da.loc[:,'Cholesterol'] = da.Cholesterol.map(mapping)

In [5]:
da.head()

Age Sex  BP  Cholesterol  Na_to_K   Drug
0   23   F   2            2   25.355  drugY
1   47   M   0            2   13.093  drugC
2   47   M   0            2   10.114  drugC
3   28   F   1            2    7.798  drugX
4   61   F   0            2   18.043  drugY

In [6]:
#from sklearn.preprocessing import OrdinalEncoder to convert text to num
from sklearn.preprocessing import LabelEncoder
cols = ['Sex'] #F/M->0/1
# Encode labels of multiple columns at once
da[cols] = da[cols].apply(LabelEncoder().fit_transform)
da.head()

Age  Sex  BP  Cholesterol  Na_to_K   Drug
0   23    0   2            2   25.355  drugY
1   47    1   0            2   13.093  drugC
2   47    1   0            2   10.114  drugC
3   28    0   1            2    7.798  drugX
4   61    0   0            2   18.043  drugY

In [7]:
map_tar ={
    'drugA':0,
    'drugB':1,
    'drugC':2,
    'drugX':3,
    'drugY':4
}

In [8]:
da.loc[:,'Drug'] = da.Drug.map(map_tar)

In [9]:
da.head()

Age  Sex  BP  Cholesterol  Na_to_K  Drug
0   23    0   2            2   25.355     4
1   47    1   0            2   13.093     2
2   47    1   0            2   10.114     2
3   28    0   1            2    7.798     3
4   61    0   0            2   18.043     4

In [10]:
#from sklearn.preprocessing import OrdinalEncoder to convert text to num
from sklearn.preprocessing import OneHotEncoder
cols = da[['Drug']]
# Encode labels
y =OneHotEncoder().fit_transform(cols).toarray()

In [11]:
y

array([[0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 0., 1.],
       [0., 0., 0., 1., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [0., 0.

In [12]:
from xgboost.sklearn import XGBClassifier

model = XGBClassifier()

In [13]:
a= list(da.columns)
for i in range (0,len(a)-1):
    print(a[i])


Age
Sex
BP
Cholesterol
Na_to_K


In [14]:
# feature selection
a= list(da.columns)
f=[]
for i in range (0,len(a)-1):
    f.append(a[i])
X = da[f]

In [15]:
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier

In [16]:
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state=1)
my_model = RandomForestClassifier(n_estimators=100,random_state=0).fit(train_X, train_y)

In [17]:
import eli5
from eli5.sklearn import PermutationImportance

perm = PermutationImportance(my_model, random_state=1).fit(test_X, test_y)
eli5.show_weights(perm, feature_names = test_X.columns.tolist())

In [18]:
# Model defination
b= list(da.columns)
f2=['Na_to_K','BP','Age','Cholesterol']
X = da[f2]
y = OneHotEncoder().fit_transform(cols).toarray()
train_X, test_X, train_y, test_y = train_test_split(X, y, random_state=1,test_size=0.22)
my_model_new = RandomForestClassifier(n_estimators=100,random_state=1).fit(train_X, train_y)

In [19]:
# model prediction
pred = my_model_new.predict(test_X)

In [20]:
pred[1]

array([0., 0., 0., 0., 1.])

In [21]:
test_y[1]

array([0., 0., 0., 0., 1.])

In [22]:
import numpy as np
np.argmax(pred[1])

4

In [23]:
np.unique(test_y)

array([0., 1.])

In [ ]:
list(pred)

In [25]:
# Evaluation Metrics 1

from Macro_Avg_Precision import macro_avg_pr
macro_avg_pr(list(test_y),pred)

0.5

In [26]:
# Evaluation Metrics 1

from Micro_Avg_Precision import micro_avg_pr
micro_avg_pr(list(test_y),pred)

1.0

In [29]:
from sklearn.model_selection import cross_val_score

cross_val_score(my_model_new,train_X,train_y,cv=5,scoring = 'accuracy')

array([0.90625   , 0.96774194, 1.        , 0.96774194, 1.        ])